#!/usr/bin/env bash
#Configure your Nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

mkdir -p /var/www/html/
chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
cat <<EOF > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /errors/404.html;
}
EOF

service nginx restart
