#!/usr/bin/env bash
# Bash script to loop from 1 to 10 and display different messages based on the loop iteration.
# On the 4th iteration, the script displays "bad luck".
# On the 8th iteration, it displays "good luck".
# For all other iterations, it displays "Best School".

count=1
while [ $count -le 10 ];
do
	if [ $count -eq 4 ]
	then
		echo bad luck
	elif [ $count -eq 8 ]
	then
		echo good luck
	else
		echo Best School
	fi
	((count++))
done
